services:
  - type: web
    name: smartfarm-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: DB_PATH
        value: /var/data

    disk:
      name: smartfarm-data
      mountPath: /var/data
      sizeGB: 1
