[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[ui]
hideTopBar = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#2ed573"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
